### ISSUE TITLE
Telegram integration

### ISSUE THREAD

**Issue by ghost** [LiveHelperChat/docker-standalone#6]
Hi 

I'm playing currently around with your docker version.
I'm testing your [telegram support](https://github.com/LiveHelperChat/telegram).
I got stuck at number 6, where there is no cron folder.  

Is it possible to use Telegram with Docker?

Thanks
Daniel

**Comment by remdex** [comment]
Better later than never :D
It should be run from container by navigating to `/code` sub folder :D There is more extensive docs now..
